/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package billykids;
import DAL.ModuloConexao;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuário
 */
public class TelaContas extends javax.swing.JInternalFrame {
    Connection conexao = null; 
    PreparedStatement pst = null; 
    ResultSet rs = null;      

    /**
     * Creates new form TelaContas
     */
    public TelaContas() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JFormattedTextField();
        txtTipo = new javax.swing.JTextField();
        txtAge = new javax.swing.JFormattedTextField();
        txtMov = new javax.swing.JFormattedTextField();
        txtNumero = new javax.swing.JFormattedTextField();
        btnConAdd = new javax.swing.JButton();
        btnConPes = new javax.swing.JButton();
        btnConEdi = new javax.swing.JButton();
        btnConDel = new javax.swing.JButton();
        btnConImp = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        txtCodigo1 = new javax.swing.JTextField();
        txtSaldo1 = new javax.swing.JFormattedTextField();
        txtTipo1 = new javax.swing.JTextField();
        txtAge1 = new javax.swing.JFormattedTextField();
        txtMov1 = new javax.swing.JFormattedTextField();
        txtNumero1 = new javax.swing.JFormattedTextField();
        btnConAdd1 = new javax.swing.JButton();
        btnConPes1 = new javax.swing.JButton();
        btnConEdi1 = new javax.swing.JButton();
        btnConDel1 = new javax.swing.JButton();
        btnConImp1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(854, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo.setBackground(new java.awt.Color(28, 28, 28));
        txtCodigo.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 122, 50, 30));

        txtSaldo.setBackground(new java.awt.Color(28, 28, 28));
        txtSaldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        txtSaldo.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtSaldo.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 152, 120, 40));

        txtTipo.setBackground(new java.awt.Color(28, 28, 28));
        txtTipo.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        txtTipo.setForeground(new java.awt.Color(255, 255, 255));
        txtTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        getContentPane().add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 192, 160, 30));

        txtAge.setBackground(new java.awt.Color(28, 28, 28));
        txtAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        txtAge.setForeground(new java.awt.Color(255, 255, 255));
        txtAge.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 222, 170, 30));

        txtMov.setBackground(new java.awt.Color(28, 28, 28));
        txtMov.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        txtMov.setForeground(new java.awt.Color(255, 255, 255));
        txtMov.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        getContentPane().add(txtMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 252, 180, 40));

        txtNumero.setBackground(new java.awt.Color(28, 28, 28));
        txtNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        txtNumero.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNumero.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 292, 150, 30));

        btnConAdd.setBackground(new java.awt.Color(28, 28, 28));
        btnConAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/Adicionar.png"))); // NOI18N
        btnConAdd.setBorder(null);
        btnConAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnConAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 70, -1));

        btnConPes.setBackground(new java.awt.Color(28, 28, 28));
        btnConPes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/Pesquisar.png"))); // NOI18N
        btnConPes.setBorder(null);
        btnConPes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConPesActionPerformed(evt);
            }
        });
        getContentPane().add(btnConPes, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 70, -1));

        btnConEdi.setBackground(new java.awt.Color(28, 28, 28));
        btnConEdi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/Editar.png"))); // NOI18N
        btnConEdi.setBorder(null);
        btnConEdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConEdiActionPerformed(evt);
            }
        });
        getContentPane().add(btnConEdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 70, -1));

        btnConDel.setBackground(new java.awt.Color(28, 28, 28));
        btnConDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/Deletar.png"))); // NOI18N
        btnConDel.setBorder(null);
        btnConDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnConDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 70, -1));

        btnConImp.setBackground(new java.awt.Color(28, 28, 28));
        btnConImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/Imprimir.png"))); // NOI18N
        btnConImp.setBorder(null);
        btnConImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConImpActionPerformed(evt);
            }
        });
        getContentPane().add(btnConImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 70, -1));

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setPreferredSize(new java.awt.Dimension(854, 480));
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigo1.setBackground(new java.awt.Color(28, 28, 28));
        txtCodigo1.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        txtCodigo1.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        jInternalFrame1.getContentPane().add(txtCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 122, 50, 30));

        txtSaldo1.setBackground(new java.awt.Color(28, 28, 28));
        txtSaldo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        txtSaldo1.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldo1.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        txtSaldo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldo1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtSaldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 152, 120, 40));

        txtTipo1.setBackground(new java.awt.Color(28, 28, 28));
        txtTipo1.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        txtTipo1.setForeground(new java.awt.Color(255, 255, 255));
        txtTipo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        jInternalFrame1.getContentPane().add(txtTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 192, 160, 30));

        txtAge1.setBackground(new java.awt.Color(28, 28, 28));
        txtAge1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        txtAge1.setForeground(new java.awt.Color(255, 255, 255));
        txtAge1.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        jInternalFrame1.getContentPane().add(txtAge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 222, 170, 30));

        txtMov1.setBackground(new java.awt.Color(28, 28, 28));
        txtMov1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        txtMov1.setForeground(new java.awt.Color(255, 255, 255));
        txtMov1.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        jInternalFrame1.getContentPane().add(txtMov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 252, 180, 40));

        txtNumero1.setBackground(new java.awt.Color(28, 28, 28));
        txtNumero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        txtNumero1.setForeground(new java.awt.Color(255, 255, 255));
        txtNumero1.setFont(new java.awt.Font("Poppins ExtraLight", 2, 20)); // NOI18N
        jInternalFrame1.getContentPane().add(txtNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 292, 150, 30));

        btnConAdd1.setBackground(new java.awt.Color(28, 28, 28));
        btnConAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/Adicionar.png"))); // NOI18N
        btnConAdd1.setBorder(null);
        btnConAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConAdd1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnConAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 70, -1));

        btnConPes1.setBackground(new java.awt.Color(28, 28, 28));
        btnConPes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/Pesquisar.png"))); // NOI18N
        btnConPes1.setBorder(null);
        btnConPes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConPes1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnConPes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 70, -1));

        btnConEdi1.setBackground(new java.awt.Color(28, 28, 28));
        btnConEdi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/Editar.png"))); // NOI18N
        btnConEdi1.setBorder(null);
        btnConEdi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConEdi1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnConEdi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, 70, -1));

        btnConDel1.setBackground(new java.awt.Color(28, 28, 28));
        btnConDel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/Deletar.png"))); // NOI18N
        btnConDel1.setBorder(null);
        btnConDel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConDel1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnConDel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 70, -1));

        btnConImp1.setBackground(new java.awt.Color(28, 28, 28));
        btnConImp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/Imprimir.png"))); // NOI18N
        btnConImp1.setBorder(null);
        btnConImp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConImp1ActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(btnConImp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 70, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/TelaContas.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, -1, 450));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtID.setBackground(new java.awt.Color(28, 28, 28));
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 28, 28)));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 322, 90, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/imagens/TelaContas.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -15, -1, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void btnConEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConEdiActionPerformed
        editar();
    }//GEN-LAST:event_btnConEdiActionPerformed

    private void btnConAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConAddActionPerformed
        cadastrar();
    }//GEN-LAST:event_btnConAddActionPerformed

    private void btnConPesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConPesActionPerformed
        buscar();
    }//GEN-LAST:event_btnConPesActionPerformed

    private void btnConDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConDelActionPerformed
        deletar();
    }//GEN-LAST:event_btnConDelActionPerformed

    private void btnConImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConImpActionPerformed
        RelContas();
    }//GEN-LAST:event_btnConImpActionPerformed

    private void txtSaldo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldo1ActionPerformed

    private void btnConAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConAdd1ActionPerformed

    private void btnConPes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConPes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConPes1ActionPerformed

    private void btnConEdi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConEdi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConEdi1ActionPerformed

    private void btnConDel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConDel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConDel1ActionPerformed

    private void btnConImp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConImp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConImp1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConAdd;
    private javax.swing.JButton btnConAdd1;
    private javax.swing.JButton btnConDel;
    private javax.swing.JButton btnConDel1;
    private javax.swing.JButton btnConEdi;
    private javax.swing.JButton btnConEdi1;
    private javax.swing.JButton btnConImp;
    private javax.swing.JButton btnConImp1;
    private javax.swing.JButton btnConPes;
    private javax.swing.JButton btnConPes1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txtAge;
    private javax.swing.JFormattedTextField txtAge1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JTextField txtID;
    private javax.swing.JFormattedTextField txtMov;
    private javax.swing.JFormattedTextField txtMov1;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JFormattedTextField txtNumero1;
    private javax.swing.JFormattedTextField txtSaldo;
    private javax.swing.JFormattedTextField txtSaldo1;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTipo1;
    // End of variables declaration//GEN-END:variables

    private void cadastrar() {
        String sql = "INSERT INTO contas (Código, Saldo, TipoConta, Agência,"
                + "Movimentação, NúmeroConta, idCliente) VALUES"
                + "(?, ?, ?, ?, ?, ?, ?)";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCodigo.getText());
            pst.setString(2, txtSaldo.getText());  //PARA COPIAR CTRL+SHIFT+SETA PRA BAIXO
            pst.setString(3, txtTipo.getText());
            pst.setString(4, txtAge.getText());
            pst.setString(5, txtMov.getText());
            pst.setString(6, txtNumero.getText());
            pst.setString(7, txtID.getText());
            
            int resultado = pst.executeUpdate();
            
            if(resultado==1){
                JOptionPane.showMessageDialog(null, "Conta cadastrada com sucesso!!");
                 txtCodigo.setText(null);
                 txtSaldo.setText(null);
                 txtTipo.setText(null);
                 txtAge.setText(null);
                 txtMov.setText(null);
                 txtNumero.setText(null);
                 txtID.setText(null);

            }else{
                JOptionPane.showMessageDialog(null, "Conta NÃO cadastrada!" );
            }
                     
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void buscar() {
        String sql= "SELECT * FROM contas WHERE Código=?";
    
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCodigo.getText());
            rs = pst.executeQuery();
            
            if(rs.next()){
                txtSaldo.setText(rs.getString("Saldo"));
                txtTipo.setText(rs.getString("TipoConta"));
                txtAge.setText(rs.getString("Agência"));
                txtMov.setText(rs.getString("Movimentação"));
                txtNumero.setText(rs.getString("NúmeroConta"));                     
                txtID.setText(rs.getString("idCliente"));                     
              
            }else{
                JOptionPane.showMessageDialog(null, "Conta não localizada!!");
                txtCodigo.setText(null);
                txtNumero.setText(null);
                txtSaldo.setText(null);
                txtAge.setText(null);
                txtTipo.setText(null);
                txtMov.setText(null);                
                txtID.setText(null);                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void editar() {
        String sql = "UPDATE contas SET Saldo=?, TipoConta=?, Agência=?,"
                + "Movimentação=?, NúmeroConta=?, idCliente=? WHERE Código=?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtSaldo.getText());  //PARA COPIAR CTRL+SHIFT+SETA PRA BAIXO
            pst.setString(2, txtTipo.getText());
            pst.setString(3, txtAge.getText());
            pst.setString(4, txtMov.getText());
            pst.setString(5, txtNumero.getText());
            pst.setString(6, txtID.getText());
            pst.setString(7, txtCodigo.getText());
            
            int atualizado = pst.executeUpdate();
            
            if(atualizado==1){
                JOptionPane.showMessageDialog(null, "Conta atualizada com sucesso!!");
                 txtCodigo.setText(null);
                 txtSaldo.setText(null);
                 txtTipo.setText(null);
                 txtAge.setText(null);
                 txtMov.setText(null);
                 txtNumero.setText(null);
                 txtID.setText(null);
                        
            }else{
                JOptionPane.showMessageDialog(null, "Conta NÃO atualizada!!" );
            }
                     
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }   
    }

    private void deletar() {
        String sql= "DELETE FROM contas WHERE Código=?";
    
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtCodigo.getText());
            int apagado = pst.executeUpdate();
            
            if(apagado>0){
                JOptionPane.showMessageDialog(null, "Conta excluída com sucesso!!");
                txtSaldo.setText(null);
                txtTipo.setText(null);
                txtAge.setText(null);
                txtMov.setText(null);
                txtNumero.setText(null);
                txtCodigo.setText(null);                          
                txtID.setText(null);                          
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }            
    }

    private void RelContas() {
        int op= JOptionPane.showConfirmDialog(null, "Confirma impressão?", "Relatório de Contas", JOptionPane.YES_NO_OPTION);
        if(op==JOptionPane.YES_OPTION){
            
            try {
                String caminho = "C:/Rel/RelContasBilly.jasper";
                JasperPrint print = JasperFillManager.fillReport(caminho, null, conexao);
                JasperViewer.viewReport(print,false);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
        }    
    } 
    
}
